services:
  - type: web
    name: LTS-Live_Talent_Sorting
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: gunicorn lts_resume_ranker.wsgi:application --workers=1 --timeout=120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: resume_ranker.settings
